### ISSUE TITLE
Cannot create new users

### ISSUE THREAD

**Issue by uncappedshady** [masterfermin02/vici-admin-them#14]
When attempting to create a new user you receive the error "USER NOT ADDED - Please go back and look at the data you entered 
user id must be between 2 and 20 characters long 
full name and password must be at least 2 characters long 
you must select a user group"

Even though all paramaters are correct it still will not create a user. only when you remove the  "require("vici-admin-them/template.php");" line can you add a user,

**Comment by masterfermin02** [comment]
issue fixed download the new version
