### ISSUE TITLE
git clone does not work..

### ISSUE THREAD

**Issue by PAOK1926** [masterfermin02/vici-admin-them#19]
when i try to get the code..

`ViciBox:/srv/www/htdocs/vicidial # git clone git@github.com:masterfermin02/vici-admin-them.git
Cloning into 'vici-admin-them'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by masterfermin02** [comment]
Hello @PAOK1926 you can also download the theme from here:
https://github.com/masterfermin02/vici-admin-them/archive/master.zip
