### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by TechRatanraj** [masterfermin02/vici-admin-them#32]
Hey- I'm getting an error after adding this in the vicidial directory. Could you please help here how this can be deployed?

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/86524062/184127365-faa3bcdf-6426-4bbc-b08e-fa9e313e0116.png">
<img width="1026" alt="Screenshot 2022-08-11 at 5 20 45 PM" src="https://user-images.githubusercontent.com/86524062/184127415-56635653-8ab7-4173-b9e1-2007e95ece34.png">
<img width="1249" alt="Screenshot 2022-08-11 at 5 22 29 PM" src="https://user-images.githubusercontent.com/86524062/184127578-3221f83c-14b6-4a6b-ad7d-ce801942b8e0.png">

**Comment by masterfermin02** [comment]
Hi, you should look for the authentication `if condition` and put this line of code inside that condition `require("vici-admin-them/template.php");`

**Comment by TechRatanraj** [comment]
Hi, I made the changes but the issue still persists. Could you please share the snapshot so that I can make the changes accordingly.
It would be a great help.

**Comment by masterfermin02** [comment]
Sure see the comments on the code:
![carbon (2)](https://user-images.githubusercontent.com/4625540/184407373-7ec76310-9937-4c4a-a389-a96320f6230f.png)

**Comment by TechRatanraj** [comment]
Now it's working fine after made the correct changes in PHP admin. 
Bro, Also how we can change the agent portal?

**Comment by masterfermin02** [comment]
For the agent portal is better to use a custom webform or something like that I will work on a responsive open source version of the agent portal, and I will let you know when it ready.
